version: '3'
services:
  app:
    #container_name: arvan_app
    build: .
#    ports:
#      - 8080:8080
    restart: on-failure
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASS=${DB_PASSWORD}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=3306
      - MYSQL_DB=${DB_NAME}
      - REDIS_PORT=6379
      - REDIS_HOST=arvan_redis
    depends_on:
      - arvan_mysql
      - arvan_redis
    networks:
      - arvan
    volumes:
    - /etc/localtime:/etc/localtime

  arvan_mysql:
    image: mysql:5.7
    container_name: arvan_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    networks:
      - arvan


  arvan_redis:
    image: redis
    container_name: arvan_redis
    ports:
      - 6379:6379
    networks:
      - arvan
    volumes:
      - /etc/localtime:/etc/localtime

  arvan_proxy:
    image: haproxy
    container_name: arvan_proxy
    ports:
      - 8080:9090
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/localtime:/etc/localtime
    networks:
      - arvan
    depends_on:
      - app

volumes:
  database_mysql:

networks:
  arvan:
    driver: bridge
